media:
  input: public/images
  output: /images

content:
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      primary: title
      fields: [title, pubDate, isDraft, author]
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Başlık
        type: string
        required: true

      - name: description
        label: Açıklama
        type: text
        required: true

      - name: pubDate
        label: Yayın Tarihi
        type: date
        required: true
        options:
          format: yyyy-MM-dd

      - name: updatedDate
        label: Güncelleme Tarihi
        type: date
        options:
          format: yyyy-MM-dd

      - name: heroImage
        label: Kapak Görseli
        type: image
        options:
          path: blog

      - name: isDraft
        label: Taslak mı?
        type: boolean
        default: true

      - name: tags
        label: Etiketler
        type: string
        list: true

      - name: author
        label: Yazar
        type: string

      - name: body
        label: İçerik
        type: rich-text
        required: true